export interface GameMeta {
  id: string;
  name: string;
  description: string;
  icon: string;
  color: string;
  category: 'arcade' | 'puzzle' | 'strategy' | 'classic';
  controls: string;
}

export const GAMES: GameMeta[] = [
  {
    id: 'snake',
    name: 'Snake',
    description: 'Eat food, grow longer, avoid walls',
    icon: '🐍',
    color: '#66bb6a',
    category: 'classic',
    controls: 'Arrows / Swipe',
  },
  {
    id: 'tetris',
    name: 'Tetris',
    description: 'Clear lines before the stack reaches the top',
    icon: '🟦',
    color: '#5c86ff',
    category: 'puzzle',
    controls: 'Arrows / Swipe',
  },
  {
    id: 'game2048',
    name: '2048',
    description: 'Merge matching tiles and reach the 2048 tile',
    icon: '🔢',
    color: '#ffa726',
    category: 'puzzle',
    controls: 'Arrows / Swipe',
  },
  {
    id: 'memory',
    name: 'Memory Match',
    description: 'Flip cards to find and match all the pairs',
    icon: '🃏',
    color: '#26c6da',
    category: 'puzzle',
    controls: 'Tap / Click',
  },
  {
    id: 'pong',
    name: 'Pong',
    description: 'Classic paddle duel against AI',
    icon: '🏓',
    color: '#26c6da',
    category: 'classic',
    controls: 'W/S or Touch',
  },
  {
    id: 'flappy',
    name: 'Flappy Bird',
    description: 'Tap to fly through the gaps between pipes',
    icon: '🐦',
    color: '#ffa726',
    category: 'arcade',
    controls: 'Tap / Space',
  },
  {
    id: 'breakout',
    name: 'Breakout',
    description: 'Bounce the ball to smash all the bricks',
    icon: '🧱',
    color: '#ef5350',
    category: 'classic',
    controls: 'Mouse / Touch',
  },
  {
    id: 'spaceinvaders',
    name: 'Space Invaders',
    description: 'Defend Earth from alien waves',
    icon: '👾',
    color: '#5c86ff',
    category: 'arcade',
    controls: 'Arrows + Space',
  },
  {
    id: 'minesweeper',
    name: 'Minesweeper',
    description: 'Find all mines without detonating',
    icon: '💣',
    color: '#ef5350',
    category: 'puzzle',
    controls: 'Tap / Click',
  },
  {
    id: 'connect4',
    name: 'Connect 4',
    description: 'Connect four in a row before the AI does',
    icon: '🔴',
    color: '#ef5350',
    category: 'strategy',
    controls: 'Tap / Click',
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    description: 'Fill every row, column and box without repeats',
    icon: '🔢',
    color: '#5c86ff',
    category: 'puzzle',
    controls: 'Tap / Click',
  },
  {
    id: 'asteroids',
    name: 'Asteroids',
    description: 'Blast asteroids, survive waves',
    icon: '☄️',
    color: '#ab47bc',
    category: 'arcade',
    controls: 'Arrows + Space',
  },
  {
    id: 'runner',
    name: 'Endless Runner',
    description: 'Jump over obstacles, go as far as you can',
    icon: '🏃',
    color: '#26c6da',
    category: 'arcade',
    controls: 'Tap / Space',
  },
  {
    id: 'chess',
    name: 'Chess',
    description: 'Play classic chess and checkmate the AI',
    icon: '♟️',
    color: '#ffa726',
    category: 'strategy',
    controls: 'Tap to move',
  },
  {
    id: 'neonblob',
    name: 'Neon Dash',
    description: 'Jump hazards, duck laser gates',
    icon: '⚡',
    color: '#26c6da',
    category: 'arcade',
    controls: 'Tap/Space Jump · ↓ Duck',
  },
];
